#!/bin/sh
# Install all dotfiles into the home directory

if [ -L "$0" ]
then
    SCRIPTSETUP="$(readlink "$0")"
else
    SCRIPTSETUP="$0"
fi

DOTFILESDIRREL=$(dirname $SCRIPTSETUP)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

[ $(uname -s) = "Darwin" ] && export MACOS=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1

for DOTFILE in *; do
    HOMEFILE="$HOME/.$DOTFILE"
    [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
    DIRFILE="$DOTFILESDIR/$DOTFILE"
    
    # Don't try to install documentation/script files
    echo $DOTFILE | egrep -q '(^script/$|\.txt$|\.md$)' && continue
    
    # Remove .sh extensions
    echo $DOTFILE | grep -q '\.sh' &&
    HOMEFILE="$HOME/.$(echo $DOTFILE | sed -e 's/\.sh//')"
    
    if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
    then
        ln -sfv "$DIRFILE" "$HOMEFILE"
    else
        rm -rv "$HOMEFILE" 2>/dev/null
        ln -sv "$DIRFILE" "$HOMEFILE"
    fi
done

HOMEDOTFILES="$HOME/.dotfiles"
if [ "$DOTFILESDIR" != "$HOMEDOTFILES" ]
then
    ln -sf "$DOTFILESDIR" "$HOMEDOTFILES"
fi

# Fix up permissions for Codespaces
if [ -n "$CODESPACES" ]
then
    chmod 700 /workspaces
fi
